headers = [
  'util.hpp',
  'log.hpp',
  'random.hpp',
  'window.hpp',

  'math/misc.hpp',
  'math/vec2.hpp',
  'math/vec3.hpp',
  'math/vec4.hpp',
  'math/mat4.hpp',

  'render/quad.hpp',
  'render/shader.hpp',
  'render/texture.hpp',
  'render/render.hpp',

  'script/ast.hpp',
  'script/cell.hpp',
  'script/lexer.hpp',
  'script/token_iterator.hpp',
  'script/parser.hpp',
  'script/registry.hpp',
  'script/vm.hpp',
  'script/script.hpp',
]
install_headers(
  headers,
  preserve_path: true,
  subdir: 'v2',
)